name = "AutoPrettyPrinting"
uuid = "9109d3c5-9510-494f-be9f-db449708e717"
authors = ["Curt Da Silva <curt.dasilva@gmail.com>"]
version = "0.1.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MacroUtilities = "274a0f0b-05f4-4024-87ff-de4a5b524b4f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[weakdeps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[extensions]
AutoPrettyPrintingDictionariesExt = "Dictionaries"
AutoPrettyPrintingTimeZonesExt = "TimeZones"

[compat]
Dates = "1"
Dictionaries = "0.3"
MacroUtilities = "1.15"
PrecompileTools = "1"
PrettyPrinting = "0.4.1"
ScopedValues = "1.2"
Sockets = "1"
TimeZones = "1"
julia = "1.9"
